"""
Feature extraction module using BioCLIP (BiomedCLIP).
Extracts joint image-text embeddings for the medical domain.
"""

import torch
import numpy as np
import open_clip
from torch.utils.data import DataLoader

from src.config import PROCESSED_DATA_DIR


class BioCLIPExtractor:
    """
    Extracts multimodal embeddings using the BiomedCLIP model.
    Maps dermatological images and clinical prompts into a shared latent space (dim 512).
    """

    def __init__(self, device: str = None):
        """
        Initializes the BiomedCLIP model and its specific tokenizer/transforms.
        """
        if device is None:
            if torch.cuda.is_available():
                self.device = torch.device("cuda")
            elif torch.backends.mps.is_available():
                self.device = torch.device("mps")
            else:
                self.device = torch.device("cpu")
        else:
            self.device = torch.device(device)
            
        print(f"Initializing BioCLIP Extractor on device: {self.device}")
        
        # Load the official BiomedCLIP model from HuggingFace via OpenCLIP
        model_name = 'hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224'
        print("Downloading/Loading BiomedCLIP weights. This may take a moment...")
        
        self.model, _, self.preprocess = open_clip.create_model_and_transforms(model_name)
        self.tokenizer = open_clip.get_tokenizer(model_name)
        
        self.model = self.model.to(self.device)
        self.model.eval()

    def get_transform(self):
        """Returns the specific image transformation required by BioCLIP."""
        return self.preprocess

    @torch.no_grad()
    def extract_from_loader(self, dataloader: DataLoader) -> tuple[np.ndarray, np.ndarray]:
        """
        Iterates over the dataloader to extract combined image and text embeddings.

        Args:
            dataloader (DataLoader): PyTorch DataLoader containing images, labels, and prompts.

        Returns:
            tuple: Extracted feature vectors (N x 512) and corresponding labels.
        """
        all_embeddings = []
        all_labels = []

        print(f"Starting BioCLIP extraction for {len(dataloader.dataset)} images...")
        
        for batch_idx, (images, labels, prompts) in enumerate(dataloader):
            images = images.to(self.device)
            
            # Tokenize the dynamic clinical text prompts generated by the DataLoader
            texts = self.tokenizer(prompts).to(self.device)
            
            # Extract features mapped to the same joint multimodal space
            image_features, text_features, logit_scale = self.model(images, texts)
            
            # Normalize features (crucial for Cosine Similarity and FAISS indexing)
            image_features /= image_features.norm(dim=-1, keepdim=True)
            
            # We retain the image features projected into the joint clinical-visual space
            combined_features = image_features.cpu().numpy()
            
            all_embeddings.append(combined_features)
            all_labels.append(labels.numpy())
            
            print(f"   Batch {batch_idx + 1}/{len(dataloader)} processed.")

        embeddings_array = np.vstack(all_embeddings)
        labels_array = np.concatenate(all_labels)
        
        return embeddings_array, labels_array

    def save_embeddings(self, embeddings: np.ndarray, labels: np.ndarray, filename_prefix: str = "bioclip"):
        """
        Saves the BioCLIP embeddings to disk.
        """
        emb_path = PROCESSED_DATA_DIR / f"{filename_prefix}_embeddings.npy"
        lbl_path = PROCESSED_DATA_DIR / f"{filename_prefix}_labels.npy"
        
        np.save(emb_path, embeddings)
        np.save(lbl_path, labels)
        print(f"Saved BioCLIP embeddings to: {emb_path}")



